version: '1'
services:
  flight-app-js:
    build:
      context: ./flight-app-js
    ports:
      - "3000:3000"

  flight-app-py:
    build:
      context: ./flight-app-py
    ports:
      - "5000:5000"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4318:4318 # OTLP http receiver
    command: ["--config", "/etc/otelcol-contrib/config.yaml"]
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=$GRAFANA_CLOUD_OTLP_ENDPOINT
      - GRAFANA_CLOUD_INSTANCE_ID=$GRAFANA_CLOUD_INSTANCE_ID
      - GRAFANA_CLOUD_API_KEY=$GRAFANA_CLOUD_API_KEY
